# Generated by Django 6.0.3 on 2026-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
    ]
